Main.Program Class Reference
Static Public Member Functions
static void Main (string[] args)
Detailed Description
Definition at line 19 of file Program.cs.
Member Function Documentation
static void Main.Program.Main (string[] args) [static]
Definition at line 21 of file Program.cs.
References Client.DBClient.ConnectToCollection(), Data.APIArgs.GetArgs(), Services.Token.TokenInformation.GetOAuthToken, Services.Proxy.ProxyInformation.GetProxyCredentials, Services.Proxy.ProxyInformation.SetValue(), and Services.Token.TokenInformation.SetValue().
The documentation for this class was generated from the following file:
FacebookApplication/Main/Program.cs