MainWindow Class Reference
Public Member Functions
MainWindow ()
Protected Member Functions
virtual void Build ()
void OnDeleteEvent (object sender, DeleteEventArgs a)
Detailed Description
Definition at line 4 of file MainWindow.cs.
Constructor & Destructor Documentation
MainWindow.MainWindow ()
Definition at line 6 of file MainWindow.cs.
References Build().
Member Function Documentation
virtual void MainWindow.Build () [protected], [virtual]
Definition at line 6 of file MainWindow.cs.
References OnDeleteEvent().
Referenced by MainWindow().
void MainWindow.OnDeleteEvent (object sender, DeleteEventArgs a) [protected]
Definition at line 11 of file MainWindow.cs.
Referenced by Build().
The documentation for this class was generated from the following file:
FacebookApplication/GUI/gtk-gui/MainWindow.cs